let plates = [{
        "name": "Alabama",
        "abbreviation": "AL",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Alaska",
        "abbreviation": "AK",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Arizona",
        "abbreviation": "AZ",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Arkansas",
        "abbreviation": "AR",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "California",
        "abbreviation": "CA",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Colorado",
        "abbreviation": "CO",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Connecticut",
        "abbreviation": "CT",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Delaware",
        "abbreviation": "DE",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Florida",
        "abbreviation": "FL",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Georgia",
        "abbreviation": "GA",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Hawaii",
        "abbreviation": "HI",
        "pointValue": 1,
        "img": "",
        "found": false
    },
    {
        "name": "Idaho",
        "abbreviation": "ID",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Illinois",
        "abbreviation": "IL",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Indiana",
        "abbreviation": "IN",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Iowa",
        "abbreviation": "IA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Kansas",
        "abbreviation": "KS",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Kentucky",
        "abbreviation": "KY",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Louisiana",
        "abbreviation": "LA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Maine",
        "abbreviation": "ME",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Maryland",
        "abbreviation": "MD",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Massachusetts",
        "abbreviation": "MA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Michigan",
        "abbreviation": "MI",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Minnesota",
        "abbreviation": "MN",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Mississippi",
        "abbreviation": "MS",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Missouri",
        "abbreviation": "MO",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Montana",
        "abbreviation": "MT",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Nebraska",
        "abbreviation": "NE",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Nevada",
        "abbreviation": "NV",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "New Hampshire",
        "abbreviation": "NH",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "New Jersey",
        "abbreviation": "NJ",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "New Mexico",
        "abbreviation": "NM",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "New York",
        "abbreviation": "NY",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "North Carolina",
        "abbreviation": "NC",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "North Dakota",
        "abbreviation": "ND",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Ohio",
        "abbreviation": "OH",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Oklahoma",
        "abbreviation": "OK",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Oregon",
        "abbreviation": "OR",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Pennsylvania",
        "abbreviation": "PA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Rhode Island",
        "abbreviation": "RI",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "South Carolina",
        "abbreviation": "SC",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "South Dakota",
        "abbreviation": "SD",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Tennessee",
        "abbreviation": "TN",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Texas",
        "abbreviation": "TX",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Utah",
        "abbreviation": "UT",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Vermont",
        "abbreviation": "VT",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Virginia",
        "abbreviation": "VA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Washington",
        "abbreviation": "WA",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "West Virginia",
        "abbreviation": "WV",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Wisconsin",
        "abbreviation": "WI",
        "pointValue": 1,
        "img": "",
        "found": false,
    },
    {
        "name": "Wyoming",
        "abbreviation": "WY",
        "pointValue": 1,
        "img": "",
        "found": false,
    }
]

for (let i = 0; i < plates.length; i++) {
    plates[i].img = `img/${plates[i].name}.png`
    plates[i].img = plates[i].img.split(" ").join("_");
}
